---
- name: Install Redis
  ansible.builtin.apt:
    name: redis-server
    state: present

- name: Ensure Redis listens on localhost and private interface
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: "bind 127.0.0.1 {{ ansible_facts['default_ipv4']['address'] }}"
  notify: Restart Redis

- name: Ensure Redis protected mode is enabled
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode '
    line: 'protected-mode yes'
  notify: Restart Redis

- name: Ensure Redis is enabled and running
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: true
