apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aegis
  namespace: argocd

spec:
  description: AEGIS GitOps deployment boundary

  sourceRepos:
    - https://github.com/EthicalNayro/AEGIS.git

  destinations:
    - namespace: aegis-system
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap

    - group: ""
      kind: Service

    - group: ""
      kind: ServiceAccount

    - group: rbac.authorization.k8s.io
      kind: Role

    - group: rbac.authorization.k8s.io
      kind: RoleBinding

    - group: batch
      kind: Job

    - group: apps
      kind: Deployment

    - group: policy
      kind: PodDisruptionBudget

    - group: networking.k8s.io
      kind: Ingress
