---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Force APT to use IPv4
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99force-ipv4
    content: 'Acquire::ForceIPv4 "true";'
    owner: root
    group: root
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install common packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - python3
    state: present
