apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-system

resources:
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - pdb.yaml
  - rq-worker.yaml
  - rq-worker-pdb.yaml
  - rq-scheduler.yaml
  - ingress.yaml

configMapGenerator:
  - name: aegis-status-page-bootstrap
    files:
      - render-configuration.py

  - name: aegis-status-page-nginx
    files:
      - default.conf=nginx.conf
