apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aegis-system

resources:
  - serviceaccount.yaml
  - migration-job.yaml
  - service.yaml
  - deployment.yaml
  - pdb.yaml
  - rq-worker.yaml
  - rq-worker-pdb.yaml
  - rq-scheduler.yaml
  - external-dns-rbac.yaml
  - external-dns-webhook-config.yaml
  - external-dns-deployment.yaml
  - ingress.yaml

configMapGenerator:
  - name: aegis-status-page-bootstrap
    files:
      - render-configuration.py

  - name: aegis-status-page-nginx
    files:
      - default.conf=nginx.conf

images:
  - name: 992382545251.dkr.ecr.us-east-1.amazonaws.com/aegis-eks-dev-status-page
    newName: 992382545251.dkr.ecr.us-east-1.amazonaws.com/aegis-eks-dev-status-page
    digest: sha256:e5c677f614969b5c18624edd77e20ef4127dc7f9500d3100289b24324d957d48