apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-status-page
  namespace: aegis-system
  labels:
    app.kubernetes.io/name: status-page
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: aegis
automountServiceAccountToken: false
