apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aegis-demo
  namespace: aegis-system
  labels:
    app.kubernetes.io/name: aegis-demo
    app.kubernetes.io/part-of: aegis

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: aegis-demo
